name: project0
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  http: ^1.1.0
  mocktail: ^1.0.1
  go_router: ^12.0.0
  flutter_riverpod: ^2.4.4
  riverpod_annotation: ^2.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  lints: ^2.1.1
  network_image_mock: ^2.0.1
  mockito: ^5.4.2
  build_runner: ^2.4.6
  riverpod_lint: ^2.1.1
  riverpod_generator: ^2.3.3
  custom_lint: ^0.5.4

flutter:
  uses-material-design: true
