// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCapXiCOE22jX7xMlits2WAm0C1dQlr19o',
    appId: '1:430358215204:web:e3adcd33543e0fcae9f6b1',
    messagingSenderId: '430358215204',
    projectId: 'matthiasp-cocktails',
    authDomain: 'matthiasp-cocktails.firebaseapp.com',
    storageBucket: 'matthiasp-cocktails.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBi6PsJMHP8a63dDrf-FlXpZiqJDbTp14E',
    appId: '1:430358215204:android:fdff53f01b1837a7e9f6b1',
    messagingSenderId: '430358215204',
    projectId: 'matthiasp-cocktails',
    storageBucket: 'matthiasp-cocktails.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQSuKB92xhexxoK3aLVMo4CseGjF3hwmY',
    appId: '1:430358215204:ios:4d9eedd8c05231b1e9f6b1',
    messagingSenderId: '430358215204',
    projectId: 'matthiasp-cocktails',
    storageBucket: 'matthiasp-cocktails.appspot.com',
    iosBundleId: 'com.example.project0',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAQSuKB92xhexxoK3aLVMo4CseGjF3hwmY',
    appId: '1:430358215204:ios:100e9ada0b75a77ee9f6b1',
    messagingSenderId: '430358215204',
    projectId: 'matthiasp-cocktails',
    storageBucket: 'matthiasp-cocktails.appspot.com',
    iosBundleId: 'com.example.project0.RunnerTests',
  );
}
